// Generated by gencpp from file planning/BuildStructureResponse.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_BUILDSTRUCTURERESPONSE_H
#define PLANNING_MESSAGE_BUILDSTRUCTURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planning
{
template <class ContainerAllocator>
struct BuildStructureResponse_
{
  typedef BuildStructureResponse_<ContainerAllocator> Type;

  BuildStructureResponse_()
    : errorCode(0)  {
    }
  BuildStructureResponse_(const ContainerAllocator& _alloc)
    : errorCode(0)  {
  (void)_alloc;
    }



   typedef int8_t _errorCode_type;
  _errorCode_type errorCode;




  typedef boost::shared_ptr< ::planning::BuildStructureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planning::BuildStructureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BuildStructureResponse_

typedef ::planning::BuildStructureResponse_<std::allocator<void> > BuildStructureResponse;

typedef boost::shared_ptr< ::planning::BuildStructureResponse > BuildStructureResponsePtr;
typedef boost::shared_ptr< ::planning::BuildStructureResponse const> BuildStructureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planning::BuildStructureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planning::BuildStructureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planning::BuildStructureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning::BuildStructureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning::BuildStructureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning::BuildStructureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::BuildStructureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::BuildStructureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planning::BuildStructureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9f50b4c26ce9db2ab6dff343915632d";
  }

  static const char* value(const ::planning::BuildStructureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9f50b4c26ce9db2ULL;
  static const uint64_t static_value2 = 0xab6dff343915632dULL;
};

template<class ContainerAllocator>
struct DataType< ::planning::BuildStructureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planning/BuildStructureResponse";
  }

  static const char* value(const ::planning::BuildStructureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planning::BuildStructureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 errorCode\n\
";
  }

  static const char* value(const ::planning::BuildStructureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planning::BuildStructureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.errorCode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BuildStructureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planning::BuildStructureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planning::BuildStructureResponse_<ContainerAllocator>& v)
  {
    s << indent << "errorCode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.errorCode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNING_MESSAGE_BUILDSTRUCTURERESPONSE_H
