// Generated by gencpp from file planning/ModelGeneratorRequest.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_MODELGENERATORREQUEST_H
#define PLANNING_MESSAGE_MODELGENERATORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planning
{
template <class ContainerAllocator>
struct ModelGeneratorRequest_
{
  typedef ModelGeneratorRequest_<ContainerAllocator> Type;

  ModelGeneratorRequest_()
    {
    }
  ModelGeneratorRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::planning::ModelGeneratorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planning::ModelGeneratorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ModelGeneratorRequest_

typedef ::planning::ModelGeneratorRequest_<std::allocator<void> > ModelGeneratorRequest;

typedef boost::shared_ptr< ::planning::ModelGeneratorRequest > ModelGeneratorRequestPtr;
typedef boost::shared_ptr< ::planning::ModelGeneratorRequest const> ModelGeneratorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planning::ModelGeneratorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planning::ModelGeneratorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planning::ModelGeneratorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning::ModelGeneratorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning::ModelGeneratorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning::ModelGeneratorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::ModelGeneratorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::ModelGeneratorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planning::ModelGeneratorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::planning::ModelGeneratorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::planning::ModelGeneratorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planning/ModelGeneratorRequest";
  }

  static const char* value(const ::planning::ModelGeneratorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planning::ModelGeneratorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::planning::ModelGeneratorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planning::ModelGeneratorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModelGeneratorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planning::ModelGeneratorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::planning::ModelGeneratorRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PLANNING_MESSAGE_MODELGENERATORREQUEST_H
