// Generated by gencpp from file planning/ModelGenerator.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_MODELGENERATOR_H
#define PLANNING_MESSAGE_MODELGENERATOR_H

#include <ros/service_traits.h>


#include <planning/ModelGeneratorRequest.h>
#include <planning/ModelGeneratorResponse.h>


namespace planning
{

struct ModelGenerator
{

typedef ModelGeneratorRequest Request;
typedef ModelGeneratorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModelGenerator
} // namespace planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planning::ModelGenerator > {
  static const char* value()
  {
    return "f50b0934fbc5c3c4cf0e84c00604ffe4";
  }

  static const char* value(const ::planning::ModelGenerator&) { return value(); }
};

template<>
struct DataType< ::planning::ModelGenerator > {
  static const char* value()
  {
    return "planning/ModelGenerator";
  }

  static const char* value(const ::planning::ModelGenerator&) { return value(); }
};


// service_traits::MD5Sum< ::planning::ModelGeneratorRequest> should match 
// service_traits::MD5Sum< ::planning::ModelGenerator > 
template<>
struct MD5Sum< ::planning::ModelGeneratorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planning::ModelGenerator >::value();
  }
  static const char* value(const ::planning::ModelGeneratorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::ModelGeneratorRequest> should match 
// service_traits::DataType< ::planning::ModelGenerator > 
template<>
struct DataType< ::planning::ModelGeneratorRequest>
{
  static const char* value()
  {
    return DataType< ::planning::ModelGenerator >::value();
  }
  static const char* value(const ::planning::ModelGeneratorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planning::ModelGeneratorResponse> should match 
// service_traits::MD5Sum< ::planning::ModelGenerator > 
template<>
struct MD5Sum< ::planning::ModelGeneratorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planning::ModelGenerator >::value();
  }
  static const char* value(const ::planning::ModelGeneratorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planning::ModelGeneratorResponse> should match 
// service_traits::DataType< ::planning::ModelGenerator > 
template<>
struct DataType< ::planning::ModelGeneratorResponse>
{
  static const char* value()
  {
    return DataType< ::planning::ModelGenerator >::value();
  }
  static const char* value(const ::planning::ModelGeneratorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNING_MESSAGE_MODELGENERATOR_H
